#!/bin/sh
#
# Home Sharing script

#Uncomment line for you emu

cam_start() {

echo "start cam"

if [ -e /var/tuxbox/config/.conf/.emu_oscam ]
	then
		/var/emu/oscam -b -c /var/keys >/dev/null &
fi

if [ -e /var/tuxbox/config/.conf/.emu_mgcamd ]
	then
		/var/emu/mgcamd >/dev/null &
fi


if [ -e /var/tuxbox/config/.conf/.emu_cccam ]
	then
		/var/emu/cccamd /var/keys/CCcam.cfg >/dev/null &
fi


if [ -e /var/tuxbox/config/.conf/.emu_wicardd ]
	then
		/var/emu/wicardd -c /var/keys/wicardd.conf >/dev/null &
		touch /tmp/ecm.info
fi

}

cam_stop() {
  
  killall -9 mgcamd >/dev/null
  killall -9 oscam >/dev/null
  killall -9 oscamemu >/dev/null
  killall -9 gbox >/dev/null
  killall -9 cs2gbox >/dev/null
  killall -9 camd3 >/dev/null
  killall -9 sbox >/dev/null
  killall -9 vizcam >/dev/null
  killall -9 cccam >/dev/null
  killall -9 wicardd >/dev/null
  killall -9 smartcard >/dev/null
	sleep 2
	rm -rf /tmp/*.info /tmp/mgcamd.pid /tmp/camd.socket /tmp/gbox.*  /tmp/share.* /tmp/*.log /tmp/*.txt

}

case $1 in
start)
	cam_start
	;;
stop)
	cam_stop
	;;
restart)
	cam_stop
	sleep 2
	cam_start
	sleep 2
	/usr/local/bin/pzapit -rz
	;;
init)
	sleep 2
	cam_start
	if grep lastChannelTVScrambled=true /var/tuxbox/config/zapit/zapit.conf
	then
		sleep 5
		/usr/local/bin/pzapit -rz
	fi	
esac

